### ISSUE TITLE
Contributing in the project 

### ISSUE THREAD

**Issue by DancingEmptier667** [librerandonaut/librerandonaut#1]
Hello! I like your app and want to contribute in translation. Is there any way that I can do it?

**Comment by librerandonaut** [comment]
Hello. Thank you for your interest. The app does not currently support multilingual capability, i.e. all texts are hardcoded in English.
Basically, you could make a fork of the github project and implement the multilingual capability and translations in it. Then we could integrate your changes back into the main development fork.
